import React, { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  ArrowLeft, ArrowRight, ChevronRight, Copy, Eye, EyeOff, GitCompareArrows,
  Grip, History, Layers3, Link2, LockKeyhole, Maximize2, Minimize2, Move,
  PanelTopClose, Pin, PinOff, Plus, RotateCcw, Search, Sparkles, Trash2, X
} from 'lucide-react';
import { ACTIVE_MODULES, FUTURE_MODULES, getModuleDefinition } from './config.js';
import {
  addModule, createId, createProject, deleteProject, duplicateModule, loadProjects,
  projectInsight, removeModule, restoreVersion, searchProjects, updateModule, updateProject
} from './projectsData.js';
import { ModuleRenderer, moduleSummary } from './ModuleHost.jsx';
import { PROJECTS_EVENT } from './summary.js';
import './projects.css';

function useProjects() {
  const [projects, setProjects] = useState(loadProjects);
  useEffect(() => { const refresh = () => setProjects(loadProjects()); window.addEventListener(PROJECTS_EVENT, refresh); window.addEventListener('storage', refresh); return () => { window.removeEventListener(PROJECTS_EVENT, refresh); window.removeEventListener('storage', refresh); }; }, []);
  return projects;
}

function useEscape(handler, enabled = true) {
  useEffect(() => { if (!enabled) return undefined; const listener = (event) => { if (event.key === 'Escape') handler(); }; window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener); }, [enabled, handler]);
}

function formatMoment(value) {
  if (!value) return 'Sin actividad';
  return new Intl.DateTimeFormat('es-CO', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
}

function SearchField({ value, onChange, placeholder }) {
  return <label className="projects-search"><Search size={14} /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>;
}

function ProjectCreator({ onClose, onCreated }) {
  const [title, setTitle] = useState(''); const [description, setDescription] = useState('');
  const create = () => { if (!title.trim()) return; const projects = createProject({ title, description }); onCreated(projects[0].id); };
  useEscape(onClose);
  return <section className="project-creator" role="dialog" aria-modal="true" aria-labelledby="creator-title"><div className="creator-ambient" /><header><button onClick={onClose}><X size={15} /> Cerrar</button><span>Nuevo universo</span><small>Siempre comienza vacío</small></header><main><div className="creator-copy"><span>Sin páginas. Sin carpetas. Sin estructura.</span><h1 id="creator-title">¿Qué vas a construir?</h1><p>Solo crearemos el espacio. La arquitectura aparecerá cuando tú decidas añadir la primera pieza.</p></div><label className="creator-name"><span>Nombre del proyecto</span><input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} onKeyDown={(event) => event.key === 'Enter' && create()} placeholder="Alemania, Empresa, Investigación…" /></label><label className="creator-description"><span>Intención opcional</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="La razón por la que este universo existe." /></label><section className="empty-project-promise"><span><Layers3 size={20} /></span><div><strong>Lienzo completamente vacío</strong><small>No añadiremos módulos, carpetas ni decisiones por ti.</small></div><i>0 piezas</i></section><button className="creator-submit" disabled={!title.trim()} onClick={create}>Entrar al espacio <ArrowRight size={14} /></button></main></section>;
}

const ProjectCard = memo(function ProjectCard({ project, onOpen }) {
  return <button className="project-universe-card" onClick={() => onOpen(project.id)}><span className="universe-rings"><i /><i /><i /></span><span className="universe-core"><Layers3 size={18} /><strong>{project.modules.filter((module) => !module.hidden).length}</strong></span><span className="universe-copy"><strong>{project.title}</strong><small>{project.description || 'Un espacio en construcción.'}</small></span><span className="universe-meta">{formatMoment(project.updatedAt)}<ChevronRight size={12} /></span></button>;
});

function ProjectsHub({ projects, onOpen, onCreate }) {
  const [query, setQuery] = useState(''); const results = useMemo(() => searchProjects(projects, query), [projects, query]);
  return <div className="projects-hub-scroll"><main className="projects-hub"><section className="projects-intro"><span>Ecosistema creativo</span><h1 id="projects-title">Proyectos</h1><p>Universos independientes para todo aquello que estás construyendo.</p><div className="projects-actions"><button onClick={onCreate}><Plus size={14} /> Crear proyecto</button><SearchField value={query} onChange={setQuery} placeholder="Buscar en todos los proyectos…" /></div></section>{query ? <section className="universal-results"><span>Búsqueda universal</span><h2>{results.length ? `${results.length} conexiones encontradas` : 'Nada coincide todavía.'}</h2><div>{results.map((result) => <button key={`${result.projectId}-${result.id}`} onClick={() => onOpen(result.projectId, result.moduleId)}><i /><span><strong>{result.title}</strong><small>{result.kind} · {result.detail}</small></span><ArrowRight size={12} /></button>)}</div></section> : null}{!projects.length ? <section className="projects-empty"><div className="empty-project-core"><Layers3 size={26} /></div><span>Sin estructura impuesta</span><h2>Tu primer universo comienza vacío.</h2><p>Añade una pieza solo cuando el proyecto la necesite.</p><button onClick={onCreate}><Plus size={14} /> Crear el primer proyecto</button></section> : <section className="project-constellation"><div className="constellation-heading"><span>Universos activos</span><h2>Lo que estás construyendo.</h2><small>{projects.length} {projects.length === 1 ? 'proyecto' : 'proyectos'}</small></div><div className="project-universe-grid">{projects.map((project) => <ProjectCard key={project.id} project={project} onOpen={onOpen} />)}<button className="project-add-orb" onClick={onCreate}><Plus size={17} /><span>Nuevo universo</span></button></div></section>}</main></div>;
}

function ModulePalette({ onClose, onAdd }) {
  const [query, setQuery] = useState(''); const needle = query.trim().toLocaleLowerCase('es');
  const active = ACTIVE_MODULES.filter((item) => !needle || `${item.title} ${item.description}`.toLocaleLowerCase('es').includes(needle));
  const future = FUTURE_MODULES.filter((item) => item.id !== 'commercial-calls' && (!needle || item.title.toLocaleLowerCase('es').includes(needle)));
  useEscape(onClose);
  return <aside className="module-palette"><header><div><span>Arquitectura modular</span><h2>Elige una pieza.</h2></div><button onClick={onClose}><X size={15} /></button></header><SearchField value={query} onChange={setQuery} placeholder="Buscar módulo…" /><div className="module-catalog"><section><h3>Disponibles ahora</h3><div>{active.map((item) => { const Icon = item.icon; return <button key={item.id} onClick={() => onAdd(item.id)}><Icon size={17} /><span><strong>{item.title}</strong><small>{item.description}</small></span><Plus size={12} /></button>; })}</div></section><section className="future-catalog"><h3>Visión del sistema</h3><div>{future.map((item) => { const Icon = item.icon; return <button key={item.id} disabled><Icon size={16} /><span><strong>{item.title}</strong><small>Próximamente</small></span><LockKeyhole size={11} /></button>; })}</div></section></div></aside>;
}

function ConnectionLayer({ modules, relations }) {
  const byId = new Map(modules.map((module) => [module.id, module]));
  return <svg className="workspace-connections" aria-hidden="true">{relations.map((relation) => { const from = byId.get(relation.from); const to = byId.get(relation.to); if (!from || !to || from.hidden || to.hidden) return null; const x1 = from.x + from.width / 2; const y1 = from.y + (from.minimized ? 31 : from.height / 2); const x2 = to.x + to.width / 2; const y2 = to.y + (to.minimized ? 31 : to.height / 2); const bend = Math.max(70, Math.abs(x2 - x1) * .42); return <g key={relation.id}><path d={`M ${x1} ${y1} C ${x1 + bend} ${y1}, ${x2 - bend} ${y2}, ${x2} ${y2}`} /><circle r="2.2"><animateMotion dur="9s" repeatCount="indefinite" path={`M ${x1} ${y1} C ${x1 + bend} ${y1}, ${x2 - bend} ${y2}, ${x2} ${y2}`} /></circle></g>; })}</svg>;
}

const ModuleWidget = memo(function ModuleWidget({ module, dimmed, onOpen, onMove, onResize, onAction, onFocus }) {
  const definition = getModuleDefinition(module.type); const Icon = definition.icon; const ref = useRef(null); const interaction = useRef(null);
  const start = (event, kind) => { if (module.pinned || window.matchMedia('(max-width: 900px)').matches) return; event.preventDefault(); event.stopPropagation(); event.currentTarget.setPointerCapture(event.pointerId); interaction.current = { kind, pointerId: event.pointerId, startX: event.clientX, startY: event.clientY, x: module.x, y: module.y, width: module.width, height: module.height }; onFocus(module.id); };
  const move = (event) => { const state = interaction.current; if (!state || state.pointerId !== event.pointerId) return; if (state.kind === 'move') ref.current?.style.setProperty('transform', `translate3d(${event.clientX - state.startX}px,${event.clientY - state.startY}px,0)`); else { ref.current?.style.setProperty('width', `${Math.max(240, state.width + event.clientX - state.startX)}px`); ref.current?.style.setProperty('height', `${Math.max(160, state.height + event.clientY - state.startY)}px`); } };
  const end = (event) => { const state = interaction.current; if (!state || state.pointerId !== event.pointerId) return; interaction.current = null; ref.current?.style.removeProperty('transform'); ref.current?.style.removeProperty('width'); ref.current?.style.removeProperty('height'); if (state.kind === 'move') onMove(module.id, Math.max(20, Math.round(state.x + event.clientX - state.startX)), Math.max(20, Math.round(state.y + event.clientY - state.startY))); else onResize(module.id, Math.max(240, Math.round(state.width + event.clientX - state.startX)), Math.max(160, Math.round(state.height + event.clientY - state.startY))); };
  return <article ref={ref} className={`workspace-widget ${module.minimized ? 'is-minimized' : ''} ${module.pinned ? 'is-pinned' : ''} ${dimmed ? 'is-dimmed' : ''}`} style={{ left: module.x, top: module.y, width: module.width, height: module.minimized ? 62 : module.height, zIndex: module.zIndex }} onPointerDown={() => onFocus(module.id)}><header><button className="widget-grip" aria-label="Mover" onPointerDown={(event) => start(event, 'move')} onPointerMove={move} onPointerUp={end}><Grip size={13} /></button><span className="widget-icon"><Icon size={14} /></span><div><strong>{module.title}</strong><small>{definition.category}{module.groupId ? ` · ${module.groupId}` : ''}</small></div><nav><button title={module.minimized ? 'Restaurar' : 'Minimizar'} onClick={() => onAction(module.id, { minimized: !module.minimized })}>{module.minimized ? <Maximize2 size={11} /> : <PanelTopClose size={11} />}</button><button title="Maximizar" onClick={() => onOpen(module.id)}><Maximize2 size={11} /></button><button title={module.pinned ? 'Desfijar' : 'Fijar'} onClick={() => onAction(module.id, { pinned: !module.pinned })}>{module.pinned ? <PinOff size={11} /> : <Pin size={11} />}</button><button title="Ocultar" onClick={() => onAction(module.id, { hidden: true })}><EyeOff size={11} /></button></nav></header>{!module.minimized ? <button className="widget-body" onClick={() => onOpen(module.id)}><span>{moduleSummary(module)}</span><i /><small>Abrir espacio</small></button> : null}{!module.minimized && !module.pinned ? <button className="widget-resize" aria-label="Redimensionar" onPointerDown={(event) => start(event, 'resize')} onPointerMove={move} onPointerUp={end}><span /></button> : null}</article>;
}, (previous, next) => previous.module.updatedAt === next.module.updatedAt && previous.module.x === next.module.x && previous.module.y === next.module.y && previous.module.width === next.module.width && previous.module.height === next.module.height && previous.module.zIndex === next.module.zIndex && previous.module.minimized === next.module.minimized && previous.module.pinned === next.module.pinned && previous.dimmed === next.dimmed);

function HistoryPanel({ project, onClose }) {
  const [compare, setCompare] = useState(null); useEscape(onClose);
  return <aside className="project-history"><header><div><span>Memoria estructural</span><h2>Versiones</h2></div><button onClick={onClose}><X size={15} /></button></header><p>El movimiento del lienzo no genera ruido. Solo los cambios reales conservan una versión.</p>{compare ? <section className="version-comparison"><GitCompareArrows size={14} /><div><strong>{compare.snapshot.modules.length} → {project.modules.length} módulos</strong><span>{compare.snapshot.title === project.title ? 'El nombre se conserva.' : `Antes: ${compare.snapshot.title}`}</span></div><button onClick={() => setCompare(null)}><X size={11} /></button></section> : null}<div>{project.history.map((version) => <article key={version.id}><i /><span><strong>{version.label}</strong><small>{formatMoment(version.at)} · {version.actor}</small></span><button onClick={() => setCompare(version)}><GitCompareArrows size={11} /> Comparar</button><button onClick={() => restoreVersion(project.id, version.id)}><RotateCcw size={11} /> Restaurar</button></article>)}</div></aside>;
}

function ModuleInspector({ project, module, onClose }) {
  const definition = getModuleDefinition(module.type); const Icon = definition.icon; const other = project.modules.filter((item) => item.id !== module.id && !item.hidden); const connected = project.relations.filter((relation) => relation.from === module.id || relation.to === module.id); const groups = [...new Set(project.modules.map((item) => item.groupId).filter(Boolean))];
  const change = useCallback((changes, reason, options) => updateModule(project.id, module.id, reason, changes, options), [module.id, project.id]);
  useEscape(onClose);
  const connect = (targetId) => { if (!targetId || connected.some((relation) => [relation.from, relation.to].includes(targetId))) return; updateProject(project.id, 'Módulos relacionados', (draft) => { draft.relations.push({ id: createId('relation'), from: module.id, to: targetId, label: 'Contexto compartido' }); return draft; }); };
  return <section className="module-inspector"><header><button onClick={onClose}><Minimize2 size={14} /> Volver al lienzo</button><div><span>{project.title}</span><i /><strong>{module.title}</strong></div><small>Guardado automático</small></header><main><section className="inspector-heading"><span className="inspector-symbol"><Icon size={22} /></span><input key={`${module.id}-${module.updatedAt}`} defaultValue={module.title} onBlur={(event) => event.target.value !== module.title && change({ title: event.target.value }, 'Módulo renombrado')} /><p>{definition.description}</p></section><section className="inspector-body"><ModuleRenderer project={project} module={module} onChange={change} /></section><section className="module-properties"><label>Vista<select value={module.view} onChange={(event) => change({ view: event.target.value }, 'Vista actualizada')}>{definition.views.map((view) => <option key={view}>{view}</option>)}</select></label><label>Agrupación<select value={module.groupId || ''} onChange={(event) => { if (event.target.value === '__new') { const name = window.prompt('Nombre del grupo'); if (name) change({ groupId: name }, 'Módulo agrupado'); } else change({ groupId: event.target.value || null }, 'Agrupación actualizada'); }}><option value="">Sin grupo</option>{groups.map((group) => <option key={group}>{group}</option>)}<option value="__new">Crear grupo…</option></select></label><label>Conectar<select defaultValue="" onChange={(event) => { connect(event.target.value); event.target.value = ''; }}><option value="">Elegir módulo…</option>{other.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><div className="property-actions"><button onClick={() => change({ pinned: !module.pinned }, module.pinned ? 'Módulo desfijado' : 'Módulo fijado')}><Pin size={11} /> {module.pinned ? 'Desfijar' : 'Fijar'}</button><button onClick={() => duplicateModule(project.id, module.id)}><Copy size={11} /> Duplicar</button><button onClick={() => { change({ hidden: true }, 'Módulo oculto'); onClose(); }}><EyeOff size={11} /> Ocultar</button><button className="is-danger" onClick={() => { if (window.confirm(`¿Eliminar “${module.title}”?`)) { removeModule(project.id, module.id); onClose(); } }}><Trash2 size={11} /> Eliminar</button></div></section>{connected.length ? <section className="module-relations"><span>Conectado con</span>{connected.map((relation) => { const id = relation.from === module.id ? relation.to : relation.from; const target = project.modules.find((item) => item.id === id); return target ? <strong key={relation.id}>{target.title}</strong> : null; })}</section> : null}</main></section>;
}

function ProjectWorkspace({ project, initialModuleId, onBack }) {
  const [palette, setPalette] = useState(false); const [history, setHistory] = useState(false); const [moduleId, setModuleId] = useState(initialModuleId); const [query, setQuery] = useState(''); const [showHidden, setShowHidden] = useState(false);
  const selected = project.modules.find((module) => module.id === moduleId); const hidden = project.modules.filter((module) => module.hidden); const visible = project.modules.filter((module) => !module.hidden || showHidden); const matches = new Set(visible.filter((module) => `${module.title} ${moduleSummary(module)}`.toLocaleLowerCase('es').includes(query.toLocaleLowerCase('es'))).map((module) => module.id));
  const surface = useMemo(() => ({ width: Math.max(1200, ...visible.map((module) => module.x + module.width + 180)), height: Math.max(820, ...visible.map((module) => module.y + (module.minimized ? 62 : module.height) + 180)) }), [visible]);
  const move = useCallback((id, x, y) => updateProject(project.id, 'Distribución actualizada', (draft) => { const source = draft.modules.find((module) => module.id === id); if (!source) return draft; const dx = x - source.x; const dy = y - source.y; draft.modules = draft.modules.map((module) => module.id === id || (source.groupId && module.groupId === source.groupId) ? { ...module, x: Math.max(20, module.x + dx), y: Math.max(20, module.y + dy) } : module); return draft; }, { history: false, activity: false }), [project.id]);
  const resize = useCallback((id, width, height) => updateModule(project.id, id, 'Tamaño actualizado', { width, height }, { history: false, activity: false }), [project.id]);
  const action = useCallback((id, changes) => updateModule(project.id, id, 'Estado del módulo actualizado', changes, { history: false, activity: false }), [project.id]);
  const focus = useCallback((id) => { const max = Math.max(1, ...project.modules.map((module) => module.zIndex || 1)); const current = project.modules.find((module) => module.id === id); if ((current?.zIndex || 1) < max) updateModule(project.id, id, 'Orden visual actualizado', { zIndex: max + 1 }, { history: false, activity: false, touch: false }); }, [project.id, project.modules]);
  const add = (type) => { addModule(project.id, type); setPalette(false); };
  return <section className="project-workspace"><header className="project-workspace-header"><button onClick={onBack}><ArrowLeft size={14} /> Proyectos</button><div><span>Universo</span><i /><input key={`${project.id}-${project.updatedAt}`} defaultValue={project.title} onBlur={(event) => event.target.value !== project.title && updateProject(project.id, 'Proyecto renombrado', (draft) => ({ ...draft, title: event.target.value }))} /></div><nav><SearchField value={query} onChange={setQuery} placeholder="Buscar en el lienzo…" /><button onClick={() => setHistory(true)}><History size={13} /> Historial</button><button onClick={() => setPalette(true)}><Plus size={13} /> Módulo</button></nav></header><div className="workspace-viewport"><div className="workspace-surface" style={{ width: surface.width, height: surface.height }}><div className="workspace-origin"><span /><strong>{project.title}</strong><small>{projectInsight(project)}</small></div><ConnectionLayer modules={visible} relations={project.relations} />{visible.map((module) => <ModuleWidget key={module.id} module={module} dimmed={Boolean(query) && !matches.has(module.id)} onOpen={setModuleId} onMove={move} onResize={resize} onAction={action} onFocus={focus} />)}{!project.modules.length ? <section className="empty-workspace"><span><Move size={24} /></span><h2>El espacio es tuyo.</h2><p>No hay una estructura correcta. Añade la primera pieza que este proyecto necesite.</p><button onClick={() => setPalette(true)}><Plus size={13} /> Explorar módulos</button></section> : null}<button className="floating-add" onClick={() => setPalette(true)}><Plus size={16} /><span>Añadir pieza</span></button></div></div>{hidden.length ? <button className="hidden-modules" onClick={() => setShowHidden(!showHidden)}>{showHidden ? <EyeOff size={13} /> : <Eye size={13} />}{showHidden ? 'Ocultar apartados' : `${hidden.length} ocultos`}</button> : null}<div className="workspace-status"><span>{project.modules.length} piezas</span><i /><span>{project.relations.length} conexiones</span><i /><span>{formatMoment(project.updatedAt)}</span></div>{palette ? <ModulePalette onClose={() => setPalette(false)} onAdd={add} /> : null}{history ? <HistoryPanel project={project} onClose={() => setHistory(false)} /> : null}{selected ? <ModuleInspector project={project} module={selected} onClose={() => setModuleId(null)} /> : null}</section>;
}

export default function ProjectsOS({ system, closing, onClose }) {
  const projects = useProjects(); const [projectId, setProjectId] = useState(null); const [initialModuleId, setInitialModuleId] = useState(null); const [creating, setCreating] = useState(false); const project = projects.find((item) => item.id === projectId);
  const open = useCallback((id, moduleId = null) => { setProjectId(id); setInitialModuleId(moduleId); }, []);
  const back = useCallback(() => { setProjectId(null); setInitialModuleId(null); }, []);
  useEscape(onClose, !project && !creating);
  return <section className={`ecosystem-world projects-os ${closing ? 'is-closing' : ''}`} style={{ '--world-origin-x': `${system.x ?? 72}%`, '--world-origin-y': `${system.y ?? 13}%` }} aria-labelledby="projects-title"><div className="world-ambient projects-ambient" />{project ? <ProjectWorkspace project={project} initialModuleId={initialModuleId} onBack={back} /> : <><header className="world-header"><button className="world-back" onClick={onClose}><ArrowLeft size={15} /> Volver al mapa</button><div className="world-location"><span>Núcleo</span><i /><strong>Proyectos</strong></div><div className="world-source"><span className={projects.length ? 'source-live' : ''} />{projects.length} {projects.length === 1 ? 'universo activo' : 'universos activos'}</div></header><ProjectsHub projects={projects} onOpen={open} onCreate={() => setCreating(true)} /></>}{creating ? <ProjectCreator onClose={() => setCreating(false)} onCreated={(id) => { setCreating(false); setProjectId(id); }} /> : null}</section>;
}
